### ISSUE TITLE
Undefined local variable or method `app_id'

### ISSUE THREAD

**Issue by johhansantana** [iffyuva/social-buttons#16]
I don't think the documentation say anything about this but this happen to me.

Also, it would be nice to have full examples with the href, text, etc. because it's a bit confusing figuring out how it really works. Right now I'm not sure how the facebook like button works becuase it is different from the other ones (it has the (app_id) and the others don't).

Thanks!

**Comment by kristianmandrup** [comment]
https://developers.facebook.com/docs/apps/register

"Choose a name for your app and select Create New Facebook App ID. Choose a category for your app. If you're creating a test version of an existing Facebook app, select the app you're testing."

You need to create a Facebook App with an App ID. The app ID on the button links to the app via this ID.

**Comment by johhansantana** [comment]
ah, so I was reading, thought it would be a bit easier, seems that I need to do some configurations. Thanks!
