### ISSUE TITLE
Which type of Facebook app?

### ISSUE THREAD

**Issue by libovness** [iffyuva/social-buttons#6]
I've implemented the gem. While the tweet button is working really well and the Like button is rendering, I don't believe that the Like button is working at all. I saw on the page (http://whoo.ps/2013/02/24/digital-salt) that it had accumulated a few Likes but there's no evidence on Facebook that anyone Liked it. If I like it myself and add text to the post it doesn't appear on Facebook.

It's possible that I have not set up my Facebook app correctly, as none of the options listed here actually seem appropriate. I've chosen "Website with Facebook Login" as it seems the _most_ appropriate, but I don't have any "login" on my site.

![Basic- Facebook Developers-1](https://f.cloud.github.com/assets/612866/200081/9ba068ca-80b8-11e2-9673-dc2978e13ea3.png)

**Comment by libovness** [comment]
This turned out to be the right choice. The problem was that I hadn't defined my fb:app_id as a metatag

**Comment by kristianmandrup** [comment]
I added your solution here: https://github.com/iffyuva/social-buttons/wiki

**Comment by libovness** [comment]
cool ^^

Note that you need to have _all_ of the following metatags for the Like
button to work.

<meta property="og:site_name" content=""/>
<meta property="og:description" content="" />
<meta property="og:url" content=""/>
<meta property="og:image" content="" />
<meta property="og:title" content="" />
<meta property="og:type" content="" />
<meta property="fb:app_id" content=""/>
<meta property="fb:admins" content=""/>

In my case I set up the Like button on each of my blog posts (see:
http://whoo.ps/blog)

On Tue, Mar 5, 2013 at 9:23 PM, Kristian Mandrup
notifications@github.comwrote:

> I added your solution here: https://github.com/iffyuva/social-buttons/wiki
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iffyuva/social-buttons/issues/6#issuecomment-14459613
> .

## 

@libovness http://twitter.com/libovness
http://whoo.ps/
+972 (0)54 813 8666

Work: http://getap.ps/appsfire
Side project: http://snapwith.me

**Comment by kristianmandrup** [comment]
Thanks. I updated the wiki accordingly :)
